status = [ "continuous-integration/travis-ci/push", "Community-TC (push)" ]
block_labels = [ "S-do-not-merge-yet" ]
cut_body_after = "<details>"
timeout_sec = 36000

[committer]
name = "Floda Reltih"
email = "flodareltih1488@protonmail.ch"
